gems: [jekyll-paginate]
title: latent.space
description: "latent.space"
#url: "http://localhost:4000"
url: latent.space
twitter_username: bcmcmahan
github_username:  braingineer
language: en_US
paginate: 10
paginate_path: "/page/:num/"
